### PR TITLE
added clusterise, pep8 style checked

### PR DESCRIPTION
**Pull request by martino-vic**
I had been using this wrapper for more than a year now and thought it would be time to suggest including it in the source package. It takes the output of ``tokenise`` and clusters consonants and vowels together. This can't be achieved with the ``merge`` argument. I've added one unittest for this function, all tests are passing. Added a description to the readme. And added ``clusterise`` and ``clusterize`` to ``__init__.py``.
Apart from that I style checked all the .py files with pep8online.com so that they all fit the pep8 standards (spaces instead of tabs, max. line length of 79 chars etc), this doesn't affect functionality.

### CODE REVIEW

**Review by martino-vic — COMMENTED** [review]
*add

**Review by pavelsof — APPROVED** [review]

**Comment by pavelsof** [comment]
Thank you very much! :green_heart: 

The new function does indeed look like a good addition to the package! I am curious: what exactly do you use the clusters for? My first thought was that inferring the vowel clusters can be used as first step in an automatic syllabification.

And thank you for moving the project to PEP8, this had been on my to-do list for way too long.

I will publish a new release before the end of the week.

**Comment by martino-vic** [comment]
Ah, I'm so happy you appreciate the changes, I was a bit nervous to be fair, as this was one of my first pull requests ever. I'm using the clusters for aligning Hungarian and Proto-Uralic words to infer (clusterwise) sound changes. The first consonant cluster of each word is paired up, the rest follows sequentially. If the two words have a different number of clusters then the difference is a suffix. (There are no prefixes in my data)

**Comment by pavelsof** [comment]
You are welcome!

Thank you for sharing! I would be curious to read more once you are done with the project – i.e. please feel free to come back in a few months to share a link :)

**Comment by martino-vic** [comment]
Yes will do so, it's all going to happen soon :)

**Pull request merged**
